# Generated by Django 3.0.7 on 2020-06-07 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='serieslocation',
            options={'verbose_name': 'Series Location', 'verbose_name_plural': 'Series Locations'},
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(null=True, upload_to='pic/cover'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('abdb264a-4b10-4ae0-b225-707d0900ccd7'), editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='SeriesLocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pic/series')),
                ('image_name', models.UUIDField(default=uuid.UUID('f89e7adc-7621-4ad8-8602-c4858e4c90e6'), editable=False, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('series_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SeriesLocation')),
            ],
            options={
                'verbose_name': 'Series Location Image',
                'verbose_name_plural': 'Series Location Images',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pic/location')),
                ('image_name', models.UUIDField(default=uuid.UUID('96a4ea9a-1761-4e52-a5c0-7493dca06c9a'), editable=False, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
            options={
                'verbose_name': 'Location Image',
                'verbose_name_plural': 'Location Images',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prefecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Prefecture')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.City'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='prefecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Prefecture'),
        ),
    ]
