# Generated by Django 3.0.7 on 2020-06-07 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200607_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('db2d989b-984b-464c-bf90-dfe6dbac5034'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('87bfd678-b30a-433f-b8e9-e08428850a15'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='serieslocationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('0b5d2f66-665b-4c67-a4d5-8933d5ebbab1'), editable=False, unique=True),
        ),
    ]
