# Generated by Django 3.0.7 on 2020-06-07 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200607_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('406ca249-db2d-4e30-b21c-21a376ef22af'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('ff14d4e7-6a08-4311-a29d-af3ff9b86ab5'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='serieslocationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('69b34c15-245f-44e3-b8d9-60d710ec91cc'), editable=False, unique=True),
        ),
    ]
