# Generated by Django 3.0.7 on 2020-06-09 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200608_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='access_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('7bb00a05-5119-4884-b4c2-b6fd937bbfc3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('1f19b572-d8d5-4fad-bc99-82625627303c'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='serieslocationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('8a12adba-4b36-43f2-b812-85229cc9a6db'), editable=False, unique=True),
        ),
    ]
