# Generated by Django 3.0.7 on 2020-06-09 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200609_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='access_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('8aebe327-d2fd-42a5-8729-40391064e155'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('77e7f2ce-509d-4825-ae3e-175505eec268'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='serieslocationimage',
            name='image_name',
            field=models.UUIDField(default=uuid.UUID('251ab8f1-2005-426b-ba8b-92927a51c359'), editable=False, unique=True),
        ),
    ]
