# Generated by Django 3.0.7 on 2020-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200713_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image_name',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_name',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='serieslocationimage',
            name='image_name',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
